version: "3"

networks:
  shared_network:
    external: true

services:
  nginx-proxy:
    build:
      context: ./LoadBalancer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - shared_network
    
    # depends_on:
    #   - web-app-applicant
    #   - workflow-service
